# Generated by Django 4.0.3 on 2022-03-22 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'api_categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Monto')),
                ('fecha', models.DateField(default=datetime.datetime(2022, 3, 22, 22, 3, 23, 634380))),
                ('tipo', models.CharField(choices=[('in', 'Ingreso'), ('out', 'Egreso')], max_length=10)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'db_table': 'api_operaciones',
                'ordering': ['concepto'],
            },
        ),
    ]
